### ISSUE TITLE
Lower cabal-version in haskell-src-1.0.3.1 (ghc 8.8)

### ISSUE THREAD

**Issue by andreasabel** [haskell-pkg-janitors/haskell-src#10]
Following https://github.com/haskell-pkg-janitors/haskell-src/issues/8#issuecomment-562895012 :
The released version haskell-src-1.0.3.1 asks for:
```
cabal-version: 2.4
```
This should be maybe lowered, since e.g. the `ghc 8.8.1` environment on travis-ci only installs `cabal 2.0`: See, e.g., https://travis-ci.org/BNFC/bnfc/jobs/622005387

**Comment by hvr** [comment]
This wouldn't be sensible as 

1. haskell-src-1.0.3.1 is a point-release made for the sole purpose of supporting (only) GHC 8.8.1
2. GHC 8.8.1 requires at least Cabal 2.4 and the `cabal-version:` is currently strongly correlated with the `lib:Cabal` version -- The Travis CI job you're referencing is using an **unsound configuration**.
3. The next minor or major release of `haskell-src` will again support a wider range of GHCs; but haskell-src-1.0.3.1 was a special release

(as pointed out in #93 this new practice to optimize the configuration space is something I've been meaning to document and elaborate upon more but haven't come around to it yet; but you'll notice that I've been using this pattern in other packages as well)

I'm therefore closing this ticket as wontfix, because the problem you're stating is not a problem with haskell-src but rather with the (wrong) assumption that it'd be sensible to use cabal 2.0 with GHC 8.8.1

I'd also like to point out that https://www.haskell.org/ghc/download_ghc_8_8_1.html clearly states that 

> ## Bundled packages and cabal-install
>
> **GHC 8.8 only works with cabal-install version 3.0 or later**. Please upgrade if you have an older version of cabal-install.
